# Generated by Django 5.1.4 on 2024-12-23 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='objects')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='object_labels')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='principles')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='skill_labels')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tongue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='tongues')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.object')),
            ],
        ),
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talking', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.memory')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='aspects',
            field=models.ManyToManyField(blank=True, to='wiki.objectlabel'),
        ),
        migrations.CreateModel(
            name='ObjectHasPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.object')),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.principle')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='principles',
            field=models.ManyToManyField(through='wiki.ObjectHasPrinciple', to='wiki.principle'),
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='wiki.object')),
                ('req_object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='needed_for', to='wiki.object')),
                ('req_label', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.objectlabel')),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.principle')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='skills')),
                ('principle1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_principle', to='wiki.principle')),
                ('principle2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_principle', to='wiki.principle')),
                ('products', models.ManyToManyField(blank=True, through='wiki.Craft', to='wiki.object')),
                ('aspects', models.ManyToManyField(blank=True, to='wiki.skilllabel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='craft',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.skill'),
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.memory')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.object')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abv', models.CharField(max_length=30)),
                ('tally', models.IntegerField()),
                ('dificulty', models.IntegerField()),
                ('reading', models.TextField(blank=True)),
                ('read', models.TextField(blank=True)),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.object')),
                ('mistery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.principle')),
                ('tongue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.tongue')),
            ],
        ),
        migrations.CreateModel(
            name='WallArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('considering', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.memory')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.object')),
            ],
        ),
    ]
