# Generated by Django 5.1.3 on 2024-11-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tongue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='aspects',
            field=models.ManyToManyField(to='wiki.objectlabel'),
        ),
        migrations.CreateModel(
            name='ObjectHasPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.object')),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.principle')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='principles',
            field=models.ManyToManyField(through='wiki.ObjectHasPrinciple', to='wiki.principle'),
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='wiki.object')),
                ('req_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needed_for', to='wiki.object')),
                ('req_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.objectlabel')),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.principle')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=200)),
                ('principle1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='wiki.principle')),
                ('principle2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='wiki.principle')),
                ('products', models.ManyToManyField(through='wiki.Craft', to='wiki.object')),
            ],
        ),
        migrations.AddField(
            model_name='craft',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.skill'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.object')),
                ('abv', models.CharField(max_length=30)),
                ('tally', models.IntegerField()),
                ('dificulty', models.IntegerField()),
                ('reading', models.TextField()),
                ('read', models.TextField()),
                ('mistery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.principle')),
                ('tongue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.tongue')),
            ],
        ),
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.object')),
                ('talking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.memory')),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.object')),
                ('consider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.memory')),
            ],
        ),
        migrations.CreateModel(
            name='WallArt',
            fields=[
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.object')),
                ('considering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.memory')),
            ],
        ),
    ]
