# Generated by Django 5.1.4 on 2025-01-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='consider',
        ),
        migrations.RemoveField(
            model_name='wallart',
            name='considering',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='wallart',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='book',
            name='obj',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books'),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='aaaaaaaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='considering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='considered', to='wiki.object'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('MEMORY', 'memory'), ('THING', 'thing'), ('BEAST', 'beast')], default='THING', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='talking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='talked', to='wiki.object'),
        ),
        migrations.DeleteModel(
            name='Beast',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
        migrations.DeleteModel(
            name='WallArt',
        ),
    ]
