# Generated by Django 5.1.4 on 2024-12-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectlabel',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='principle',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skilllabel',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tongue',
            name='des',
            field=models.TextField(),
        ),
    ]
