# Generated by Django 5.1.4 on 2024-12-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_object_des_alter_objectlabel_des_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='des',
        ),
        migrations.RemoveField(
            model_name='objectlabel',
            name='des',
        ),
        migrations.RemoveField(
            model_name='principle',
            name='des',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='des',
        ),
        migrations.RemoveField(
            model_name='skilllabel',
            name='des',
        ),
        migrations.RemoveField(
            model_name='tongue',
            name='des',
        ),
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/objects'),
        ),
        migrations.AddField(
            model_name='objectlabel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='objectlabel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/object_labels'),
        ),
        migrations.AddField(
            model_name='principle',
            name='descriptioncription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='principle',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/principles'),
        ),
        migrations.AddField(
            model_name='skill',
            name='aspects',
            field=models.ManyToManyField(blank=True, to='wiki.skilllabel'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/skills'),
        ),
        migrations.AddField(
            model_name='skilllabel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skilllabel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/skill_labels'),
        ),
        migrations.AddField(
            model_name='tongue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tongue',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/tongues'),
        ),
        migrations.AlterField(
            model_name='beast',
            name='talking',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.memory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='read',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='reading',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tongue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.tongue'),
        ),
        migrations.AlterField(
            model_name='craft',
            name='req_label',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.objectlabel'),
        ),
        migrations.AlterField(
            model_name='craft',
            name='req_object',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='needed_for', to='wiki.object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='aspects',
            field=models.ManyToManyField(blank=True, to='wiki.objectlabel'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='principle1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_principle', to='wiki.principle'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='principle2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_principle', to='wiki.principle'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='products',
            field=models.ManyToManyField(blank=True, through='wiki.Craft', to='wiki.object'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='consider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.memory'),
        ),
        migrations.AlterField(
            model_name='wallart',
            name='considering',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.memory'),
        ),
    ]
