# Generated by Django 5.1.4 on 2025-01-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_remove_memory_obj_remove_thing_consider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.object'),
        ),
    ]
