# Generated by Django 5.1.4 on 2025-01-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_book_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tongue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.tongue'),
        ),
    ]
