# Generated by Django 5.1.4 on 2024-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_object_des_remove_objectlabel_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='image',
            field=models.ImageField(blank=True, upload_to='principles'),
        ),
    ]
