# Generated by Django 5.1.4 on 2024-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_principle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principle',
            old_name='descriptioncription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, upload_to='objects'),
        ),
        migrations.AlterField(
            model_name='objectlabel',
            name='image',
            field=models.ImageField(blank=True, upload_to='object_labels'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='skills'),
        ),
        migrations.AlterField(
            model_name='skilllabel',
            name='image',
            field=models.ImageField(blank=True, upload_to='skill_labels'),
        ),
        migrations.AlterField(
            model_name='tongue',
            name='image',
            field=models.ImageField(blank=True, upload_to='tongues'),
        ),
    ]
