# Generated by Django 5.1.6 on 2025-02-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_book_tongue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objecthasprinciple',
            unique_together={('obj', 'principle')},
        ),
    ]
