# Generated by Django 5.1.6 on 2025-02-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_objecthasprinciple_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecthasprinciple',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.object'),
        ),
    ]
