# Generated by Django 5.1.6 on 2025-03-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_objecthasprinciple_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='wisdom1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='wisdom2',
            field=models.TextField(blank=True),
        ),
    ]
