# Generated by Django 5.1.6 on 2025-03-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_skill_wisdom1_skill_wisdom2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='objectlabel',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='principle',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='skilllabel',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tongue',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
