# Generated by Django 5.2.1 on 2025-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_alter_book_name_alter_object_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='object',
            name='principles',
            field=models.ManyToManyField(blank=True, through='wiki.ObjectHasPrinciple', to='wiki.principle'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='products',
            field=models.ManyToManyField(blank=True, through='wiki.Craft', through_fields=('skill', 'product'), to='wiki.object'),
        ),
    ]
